%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 809.297732746243
Camera1.fy: 805.481671359985
Camera1.cx: 760.821046893386
Camera1.cy: 604.951918893599

Camera1.k1: -0.026756515108645
Camera1.k2: 0.0594465946453688
Camera1.k3: -0.026436135919349
Camera1.p1: 0.00119315394105126
Camera1.p2: -0.00505107520045198

Camera2.fx: 803.419363540967
Camera2.fy: 800.650132310305
Camera2.cx: 758.276578592801
Camera2.cy: 608.95578048585

Camera2.k1: -0.0155659985729478
Camera2.k2: 0.0522682184314098
Camera2.k3: -0.0257297008857971
Camera2.p1: 0.00235336629690682
Camera2.p2: -0.00803604183351545

Camera.width: 1600
Camera.height: 1200

# Camera frames per second
Camera.fps: 60

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 60.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.999985308559617, -0.00190467099643176, 0.00507492791316807, -99.3158463669498e-3,
         0.00194902766207569, 0.999959820413783, -0.00874979138078268, -0.477312790389296e-3,
         -0.00505805853079663, 0.00875955400863005, 0.999948841820155, -1.51008603960185e-3,
         0, 0, 0, 1.000000000000000]
         
         # Transformation from camera to IMU
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [-0.011235092332746804, 0.9998907174198297, 0.009608637672980591, 0.05320347142186549,
         0.0006083771798949811, 0.009616077677691182, -0.999953579386214, -0.0007188769018119753,
         -0.9999366992852495, -0.011228725116974647, -0.0007163482154548262, -0.06763835411845474,
         0.0, 0.0, 0.0, 1.0]

# IMU noise parameters
IMU.NoiseAcc: 0.0022805084626578718
IMU.AccWalk: 5.8837296526825724e-05
IMU.NoiseGyro: 0.00014384629116236022
IMU.GyroWalk: 6.647710518330512e-07
IMU.Frequency: 2000.0
         
         

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0
